version: '3.9'

services:
  mongodb:
    image: mongo:6.0.6
    ports:
      - 27017:27017
    enviroment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ESS10W@A
    volumes: 
      -  ./mongo_data:/data/db